version: '3.8'

services:
  # Relational Database for ACID compliance
  postgres:
    image: postgres:15-alpine
    container_name: irctc_postgres
    environment:
      POSTGRES_USER: smith
      POSTGRES_PASSWORD: Smith.123
      POSTGRES_DB: irctc_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Distributed Cache and Locking Mechanism
  redis:
    image: redis:7-alpine
    container_name: irctc_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  pg_data:
  redis_data: